---
name: "Apply and test code quality"
description: "Lint, format, and test code on push and pull request events, committing fixes and formatted file(s)."
permissions: {}

on:
  push:
  pull_request:

jobs:
  lint-and-format:
    name: "Lint and format"
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: write
      pull-requests: write
      security-events: write

    steps:
      - name: "Create GitHub app token"
        id: github_app_token
        if: ${{ env.ACT != 'true' }}
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.BYPASS_RULES_APP_ID }}
          private-key: ${{ secrets.BYPASS_RULES_APP_PRIVATE_KEY }}
          permission-actions: read
          permission-members: read
          permission-metadata: read
          permission-contents: write
          permission-pull-requests: write
          permission-email-addresses: read
          permission-security-events: write

      - name: "Checkout repository"
        uses: actions/checkout@v5
        with:
          token: ${{ (steps.github_app_token.conclusion == 'skipped' && github.token) || steps.github_app_token.outputs.token }}
          fetch-depth: 0
          persist-credentials: false

      - name: "Install Node.js"
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: "Install Bun"
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.3"

      - name: "Install Go"
        uses: actions/setup-go@v6
        with:
          go-version-file: "./backend/go.mod"

      - name: "Lint and format files"
        run: |
          bun add --dev prettier@^3 prettier-plugin-astro@^0 @biomejs/biome@^2
          bun run prettier . --write --ignore-unknown --no-error-on-unmatched-pattern
          bun run --bun biome check --write --no-errors-on-unmatched
          rm -rf ./node_modules/ ./bun.lock ./package.json

      - name: "Lint and format Golang files"
        uses: golangci/golangci-lint-action@v9
        with:
          args: "--fix"
          working-directory: "./backend/"

      - name: "Lint Dependabot file and GitHub Actions workflows"
        uses: zizmorcore/zizmor-action@e639db99335bc9038abc0e066dfcd72e23d26fb4 # v0.3.0
        with:
          version: "v1.16.3"
          advanced-security: ${{ env.ACT != 'true' }}

      - name: "Scan for leaked secrets"
        uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2.3.9
        env:
          GITHUB_TOKEN: ${{ (steps.github_app_token.conclusion == 'skipped' && github.token) || steps.github_app_token.outputs.token }}
          GITLEAKS_VERSION: "8.30.0"
          GITLEAKS_NOTIFY_USER_LIST: "@hozlucas28"
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: ${{ env.ACT != 'true' }}

      - name: "Push fixes and formatted file(s)"
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          skip_push: ${{ env.ACT == 'true' }}
          commit_message: "ci: fix and format"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"

  test-frontend:
    name: "Run Frontend tests"
    runs-on: ubuntu-latest

    needs: lint-and-format

    permissions:
      contents: read

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Install Node.js"
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: "Install Bun"
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "1.3.3"

      - name: "Install dependencies"
        run: |
          cd ./frontend/
          bun ci

      - name: "Run tests"
        run: |
          cd ./frontend/
          bun test

  test-backend:
    name: "Run Backend tests"
    runs-on: ubuntu-latest

    needs: lint-and-format

    permissions:
      contents: read

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: "Install Go"
        uses: actions/setup-go@v6
        with:
          go-version-file: "./backend/go.mod"

      - name: "Run tests"
        run: |
          cd ./backend/
          go test ./...

env:
  CI: true
  LEFTHOOK: 0

concurrency:
  group: ${{ github.ref }}_apply-and-test-code-quality
  cancel-in-progress: true
