---
name: Format
run-name: Format files
description: Formats files on push to main branch.
permissions: {}

on:
  push:
    branches:
      - main

jobs:
  format:
    name: Format files
    runs-on: ubuntu-latest

    permissions:
      contents: write # To commit and push formatted files

    steps:
      - name: Create GitHub app token
        id: github-app-token
        if: ${{ env.ACT != 'true' }}
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.BYPASS_RULES_APP_ID }}
          private-key: ${{ secrets.BYPASS_RULES_APP_PRIVATE_KEY }}
          permission-contents: write

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ (steps.github-app-token.conclusion == 'skipped' && github.token) || steps.github-app-token.outputs.token }}
          persist-credentials: true

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24 # Latest patch and minor of Node.js 24

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.3

      - name: Install Go
        uses: actions/setup-go@v6
        with:
          token: ${{ (steps.github-app-token.conclusion == 'skipped' && github.token) || steps.github-app-token.outputs.token }}
          go-version-file: backend/go.mod
          cache-dependency-path: backend/go.sum

      - name: Install Prettier and Biome
        run: bun add --dev prettier@^3 prettier-plugin-astro@^0 @biomejs/biome@^2

      - name: Install Golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest
          github-token: ${{ (steps.github-app-token.conclusion == 'skipped' && github.token) || steps.github-app-token.outputs.token }}
          working-directory: backend

      - name: Format files
        run: |
          bun run prettier --write --ignore-unknown --no-error-on-unmatched-pattern .
          bun run --bun biome format --write --no-errors-on-unmatched .
          cd backend/
          golangci-lint fmt ./...

      - name: Push fixes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          skip_push: ${{ env.ACT == 'true' }}
          commit_message: "ci: format files"
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com

env:
  CI: true
  LEFTHOOK: 0

concurrency:
  group: format
  cancel-in-progress: true
