---
name: Label
run-name: Label
description: Labels pull request based on changed files when it is opened, reopened, or synchronized.
permissions: {}

on:
  pull_request_target:
    branches-ignore:
      - hozlucas28/github-action/workflow-test

jobs:
  label:
    name: Label pull request
    runs-on: ubuntu-latest

    if: ${{ github.repository == 'hozlucas28/UNLaM-Calendar' }}

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout labeler configuration
        uses: actions/checkout@v6
        with:
          sparse-checkout: .github/labeler.yml
          persist-credentials: false
          sparse-checkout-cone-mode: false

      - name: Label pull request
        uses: actions/labeler@v6

concurrency:
  group: ${{ github.event.pull_request.number }}_label
  cancel-in-progress: true
