---
name: Lint and Test Frontend
run-name: Lint and Test Frontend
description: Lints Frontend changed files (applying safe fixes) and tests it when code is pushed or a pull request is opened, reopened or synchronized.
permissions: {}

on:
  push:
    paths:
      - frontend/**/*
    branches-ignore:
      - hozlucas28/github-action/workflow-test

  pull_request:
    paths:
      - frontend/**/*
    branches-ignore:
      - hozlucas28/github-action/workflow-test

jobs:
  lint-changed-files:
    name: Lint Frontend changed files
    runs-on: ubuntu-latest

    permissions:
      contents: write # To commit and push fixes

    steps:
      - name: Create GitHub app token
        id: github-app-token
        if: ${{ env.ACT != 'true' }}
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.BYPASS_RULES_APP_ID }}
          private-key: ${{ secrets.BYPASS_RULES_APP_PRIVATE_KEY }}
          permission-contents: write

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: ${{ (github.event_name == 'pull_request' && github.head_ref) || '' }}
          token: ${{ (steps.github-app-token.conclusion == 'skipped' && github.token) || steps.github-app-token.outputs.token }}
          fetch-depth: 0
          persist-credentials: true

      - name: Install Biome
        uses: biomejs/setup-biome@v2
        with:
          token: ${{ (steps.github-app-token.conclusion == 'skipped' && github.token) || steps.github-app-token.outputs.token }}
          version: ^2

      - name: Lint Frontend changed files
        run: biome lint --fix $CONDITIONAL_ARGS --no-errors-on-unmatched frontend
        env:
          CONDITIONAL_ARGS: ${{ (github.event_name == 'pull_request' && format('--changed --vcs-default-branch=origin/{0}', github.event.pull_request.base.ref)) || ''}}

      - name: Push fixes
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          skip_push: ${{ env.ACT == 'true' }}
          file_pattern: frontend/**/*
          commit_message: "ci(frontend): apply safe fixes"
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com

  test:
    name: Test Frontend
    runs-on: ubuntu-latest

    needs: lint-changed-files

    permissions:
      contents: read # To checkout the repository

    steps:
      - name: Checkout frontend directory
        uses: actions/checkout@v6
        with:
          ref: ${{ (github.event_name == 'pull_request' && github.head_ref) || '' }}
          sparse-checkout: frontend
          persist-credentials: false
          sparse-checkout-cone-mode: false

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24 # Latest patch and minor of Node.js 24

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.3

      - name: Install Frontend dependencies
        run: bun ci
        working-directory: frontend

      - name: Test Frontend
        run: bun test
        working-directory: frontend

env:
  CI: true
  LEFTHOOK: 0

concurrency:
  group: lint-and-test-frontend_${{ (github.event_name == 'push' && github.ref) || github.event.pull_request.number }}
  cancel-in-progress: true
