---
name: "Lint pull request"
description: "Lint pull request on create or update it."
permissions: {}

on:
  pull_request:

jobs:
  lint-pull-request:
    name: "Lint pull request"
    runs-on: ubuntu-latest

    if: ${{ github.actor != 'dependabot[bot]' }}

    permissions:
      pull-requests: read

    steps:
      - name: "Lint pull request branch name"
        uses: deepakputhraya/action-branch-name@e0f8db53a8e289f1ae6f6c3e8dc70a3d366fd876
        with:
          regex: '\/.+'
          allowed_prefixes: ${{ github.actor }}

concurrency:
  group: ${{ github.ref }}_lint-pull-request
  cancel-in-progress: true
