---
name: Stale
run-name: Stale pull requests and issues
description: Stales pull requests and issues after a period of inactivity.
permissions: {}

on:
  schedule:
    - cron: 0 8 * * *

jobs:
  stale:
    name: Stale pull requests and issues
    runs-on: ubuntu-latest

    permissions:
      issues: write # To mark issues as stale
      actions: write # Not specified in https://github.com/actions/stale/
      pull-requests: write # To mark pull requests as stale

    steps:
      - uses: actions/stale@v10
        with:
          days-before-stale: 7
          days-before-close: -1
          stale-pr-label: stale
          stale-issue-label: stale
          exempt-pr-labels: bot
          exempt-issue-labels: bot
          stale-pr-message: This pull request has been marked as stale due to inactivity.
          stale-issue-message: This issue has been marked as stale due to inactivity.
          exempt-draft-pr: true
